name: Wakatime Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  update-readme:
    name: Profile Readme Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          BADGE_STYLE: "for-the-badge"
          COMMIT_MESSAGE: "docs: wakatime update :robot:"
          GH_TOKEN: ${{ secrets.GH_TOKEN  }}
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_OS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_TIMEZONE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_UPDATED_DATE: "False"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
